# helm/discourse/Chart.yaml
apiVersion: v2
name: discourse
description: A Helm chart for Discourse
type: application
version: 0.1.0
appVersion: "3.2.1"

dependencies:
  - name: postgresql
    version: 12.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 17.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
