
gems:
  - actioncable
  - actionmailer
  - actionpack
  - actionview
  - activejob
  - activemodel
  - activerecord
  - activestorage
  - activesupport
  - aws-sdk-s3
  - bundler
  - connection_pool
  - discourse_image_optim
  - excon
  - execjs
  - fast_blank
  - fastimage
  - highline
  - htmlentities
  - image_optim
  - image_size
  - mail
  - memory_profiler
  - message_bus
  - mini_mime
  - mini_racer
  - mini_scheduler
  - mini_suffix
  - multi_json
  - mustache
  - nokogiri
  - oj
  - omniauth
  - pg
  - pry-rails
  - puma
  - r2
  - rack
  - rack-mini-profiler
  - rack-protection
  - rails_multisite
  - rake
  - redis
  - rinku
  - rotp
  - rqrcode
  - sidekiq
  - thor
  - tilt
