
dependencies:
  "@discourse/moment-timezone-names-translations": "^1.0.0"
  "@fortawesome/fontawesome-free": "^5.15.4"
  "@json-editor/json-editor": "^2.6.1"
  "@popperjs/core": "^2.11.2"
  "ace-builds": "^1.4.12"
  "bootbox": "^5.5.2"
  "chart.js": "^3.7.0"
  "discourse-common": "1.0.0"
  "ember-cli": "^3.28.0"
  "ember-source": "^3.28.0"
  "handlebars": "^4.7.7"
  "highlight.js": "^10.7.3"
  "jquery": "^3.6.0"
  "message-bus-client": "^3.3.0"
  "pikaday": "^1.8.2"
  "select2": "^4.0.13"
  "workbox-webpack-plugin": "^6.4.2"
