# k8s/base/volumes.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: discourse-uploads
  namespace: discourse
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: discourse-backups
  namespace: discourse
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 20Gi
