version: '3.8'

services:
  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: discourse
      POSTGRES_PASSWORD: discourse
      POSTGRES_DB: discourse
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U discourse"]
      interval: 5s
      timeout: 3s
      retries: 5

  discourse:
    image: discourse:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      - DISCOURSE_DB_HOST=postgres
      - DISCOURSE_DB_NAME=discourse
      - DISCOURSE_DB_USERNAME=discourse
      - DISCOURSE_DB_PASSWORD=discourse
      - DISCOURSE_REDIS_HOST=redis
      - DISCOURSE_HOSTNAME=localhost
      - RAILS_ENV=production
    volumes:
      - discourse_data:/var/lib/discourse
      - discourse_logs:/var/log/discourse
      - discourse_tmp:/var/tmp/discourse

volumes:
  postgres_data:
  redis_data:
  discourse_data:
  discourse_logs:
  discourse_tmp:
