# .github/workflows/policy-checks.yml
name: Policy Checks

on:
  pull_request:
    paths:
      - '**.yaml'
      - '**.yml'
      - 'Dockerfile'
      - '*.nix'

jobs:
  conftest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Conftest
        run: |
          wget https://github.com/open-policy-agent/conftest/releases/download/v0.42.1/conftest_0.42.1_Linux_x86_64.tar.gz
          tar xzf conftest_0.42.1_Linux_x86_64.tar.gz
          sudo mv conftest /usr/local/bin/

      - name: Run Policy Checks
        run: |
          make test-all

      - name: Report Results
        if: always()
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const results = JSON.parse(fs.readFileSync('conftest-results.json', 'utf8'));
            const summary = createPolicyCheckSummary(results);
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: summary
            });